apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: database-project
  namespace: argo-cd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  description: Database components project.

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
