argo-cd:
  dex:
    enabled: false

  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$/jMcziaWt0f3p5FsFdDn9uVTk3W7ZBoU9R8vSmYDjvn9ygt5Dj8s6"

  server:
    extraArgs:
      - --insecure
